package ch.heigvd.amt.gamification;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * @author Sébastien Richoz
 * @version 1.0
 * @date 14.12.2016
 */
@Entity
@Table(name = "caca")
public class ExampleUser {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    @NotNull
    private String email;

    @NotNull
    private String name;

    // Public methods

    public ExampleUser() { }

    public ExampleUser(long id) {
        this.id = id;
    }

    public ExampleUser(String email, String name) {
        this.email = email;
        this.name = name;
    }

    // Getter and setter methods
    public long getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public String getName() {
        return name;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setName(String name) {
        this.name = name;
    }
}
