version: '2'
services:
  wildfly:
    build: ./docker/wildfly
    ports:
     - "9090:8080"
     - "9990:9990"
    links:
     - mysql:db
  mysql:
    build: ./docker/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - "3306:3306"
  phpmyadmin:
    build: ./docker/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - "6060:80"
    links:
     - mysql:db
