version: '2'
services:
  java:
    build:
      context: ./
      dockerfile: ./images/java/Dockerfile
    ports:
     - "8080:8080"
    links:
     - mysql:db
  mysql:
    build: ./images/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - "3306:3306"
  phpmyadmin:
    build: ./images/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - "6060:80"
    links:
     - mysql:db
